### ISSUE TITLE
Https not supported

### ISSUE THREAD

**Issue by msnv** [wqweto/VbAsyncSocket#2]
Hi,
Why HTTPs protocol is not supported in download class?
best reguard

**Comment by wqweto** [comment]
The https protocol is not supported in `cHttpDownload` class because current `cTlsClient` supports only synchronous calls while the `cHttpDownload` class implements upload and download operations asychronously.

When someone sends a Pull Request w/ asychronous TLS client class, then `cHttpDownload` calss can be easily based on it for both http and https support.

**Comment by wqweto** [comment]
FYI, latest version of `cHttpDownload` is re-based on the new `cTlsSocket` class and officially supports https encrypted downloads and uploads.

**Comment by M2000Interpreter** [comment]
Thanks
